/**
 * Submission Pack Generator
 * Creates a ZIP file with all submission materials
 */

import fs from "fs";
import path from "path";
import archiver from "archiver";
import type { RuleEvaluationResult, SubmissionPack, GateFinding } from "@storepreflight/shared";
import { createPackFilename } from "@storepreflight/shared";
import { generateHtmlReport } from "./htmlReport.js";

export interface SubmissionPackOptions {
  /** Rule evaluation result */
  result: RuleEvaluationResult;
  /** Output directory for the ZIP */
  outputDir: string;
  /** Optional processed assets directory */
  assetsDir?: string;
}

/**
 * Generate copy-paste text files from findings
 */
function generateCopyPasteFiles(findings: GateFinding[]): Map<string, string> {
  const files = new Map<string, string>();

  // Collect all copy text by type
  const appPurposes: string[] = [];
  const permissionJustifications: string[] = [];
  const reviewerNotes: string[] = [];
  const dataSafetyEntries: Record<string, string> = {};

  for (const finding of findings) {
    if (finding.copy.appPurpose) {
      appPurposes.push(`[${finding.id}]\n${finding.copy.appPurpose}`);
    }
    if (finding.copy.permissionJustification) {
      permissionJustifications.push(`[${finding.id}]\n${finding.copy.permissionJustification}`);
    }
    if (finding.copy.reviewerNotes) {
      reviewerNotes.push(`[${finding.id}]\n${finding.copy.reviewerNotes}`);
    }
    if (finding.copy.dataSafety) {
      dataSafetyEntries[finding.id] = finding.copy.dataSafety;
    }
  }

  if (appPurposes.length > 0) {
    files.set("google_app_purpose.txt", appPurposes.join("\n\n---\n\n"));
  }

  if (permissionJustifications.length > 0) {
    files.set("google_permission_justifications.txt", permissionJustifications.join("\n\n---\n\n"));
  }

  if (reviewerNotes.length > 0) {
    files.set("reviewer_notes.txt", reviewerNotes.join("\n\n---\n\n"));
  }

  if (Object.keys(dataSafetyEntries).length > 0) {
    files.set("data_safety.json", JSON.stringify(dataSafetyEntries, null, 2));
  }

  return files;
}

/**
 * Generate platform-specific checklists
 */
function generateChecklists(result: RuleEvaluationResult): Map<string, string> {
  const checklists = new Map<string, string>();

  const googleFindings = result.findings.filter(
    (f) => f.platform === "google" || f.platform === "both"
  );

  const appleFindings = result.findings.filter(
    (f) => f.platform === "apple" || f.platform === "both"
  );

  if (result.platformTargets.includes("android")) {
    const items = googleFindings.map((f) => {
      const checks: string[] = [];
      if (f.requires.video) checks.push("Upload YouTube demo video");
      if (f.requires.screenshots) checks.push("Prepare screenshots");
      if (f.requires.reviewerNotes) checks.push("Add reviewer notes");
      if (f.copy.permissionJustification) checks.push("Add permission justification");
      if (f.copy.dataSafety) checks.push("Complete Data Safety form");

      return `## ${f.id}\n\n${checks.map((c) => `- [ ] ${c}`).join("\n")}`;
    });

    checklists.set(
      "google-play.md",
      `# Google Play Console Checklist\n\nGenerated by StorePreflight\n\n${items.join("\n\n")}`
    );
  }

  if (result.platformTargets.includes("ios")) {
    const items = appleFindings.map((f) => {
      const checks: string[] = [];
      if (f.requires.screenshots) checks.push("Prepare screenshots");
      if (f.requires.reviewerNotes) checks.push("Add App Review notes");
      if (f.copy.permissionJustification) checks.push("Add usage description");

      return `## ${f.id}\n\n${checks.map((c) => `- [ ] ${c}`).join("\n")}`;
    });

    checklists.set(
      "app-store.md",
      `# App Store Connect Checklist\n\nGenerated by StorePreflight\n\n${items.join("\n\n")}`
    );
  }

  return checklists;
}

/**
 * Generate the complete submission pack ZIP
 */
export async function generateSubmissionPack(
  options: SubmissionPackOptions
): Promise<SubmissionPack> {
  const { result, outputDir, assetsDir } = options;

  // Ensure output directory exists
  fs.mkdirSync(outputDir, { recursive: true });

  const zipFilename = createPackFilename(result.appName);
  const zipPath = path.join(outputDir, zipFilename);

  return new Promise((resolve, reject) => {
    const output = fs.createWriteStream(zipPath);
    const archive = archiver("zip", { zlib: { level: 9 } });

    const copyPasteFiles: string[] = [];
    const screenshots: string[] = [];
    const checklists: string[] = [];
    let hasFeatureGraphic = false;
    let hasIcon = false;

    output.on("close", () => {
      resolve({
        appName: result.appName,
        generatedAt: new Date().toISOString(),
        zipPath,
        contents: {
          hasReport: true,
          copyPasteFiles,
          screenshots,
          hasFeatureGraphic,
          hasIcon,
          checklists,
        },
      });
    });

    archive.on("error", (err) => {
      reject(err);
    });

    archive.pipe(output);

    // Add HTML report
    const htmlReport = generateHtmlReport(result);
    archive.append(htmlReport, { name: "reports/storepreflight.html" });

    // Add copy-paste files
    const copyFiles = generateCopyPasteFiles(result.findings);
    for (const [filename, content] of copyFiles) {
      archive.append(content, { name: `copy-paste/${filename}` });
      copyPasteFiles.push(filename);
    }

    // Add checklists
    const checklistFiles = generateChecklists(result);
    for (const [filename, content] of checklistFiles) {
      archive.append(content, { name: `checklists/${filename}` });
      checklists.push(filename);
    }

    // Add processed assets if provided
    if (assetsDir && fs.existsSync(assetsDir)) {
      const screenshotsDir = path.join(assetsDir, "screenshots");
      if (fs.existsSync(screenshotsDir)) {
        const files = fs.readdirSync(screenshotsDir);
        for (const file of files) {
          const filePath = path.join(screenshotsDir, file);
          archive.file(filePath, { name: `assets/google-play/screenshots/${file}` });
          screenshots.push(file);
        }
      }

      const featureGraphicPath = path.join(assetsDir, "feature-graphic.jpg");
      if (fs.existsSync(featureGraphicPath)) {
        archive.file(featureGraphicPath, { name: "assets/feature-graphic.jpg" });
        hasFeatureGraphic = true;
      }

      const iconPath = path.join(assetsDir, "icon-512.png");
      if (fs.existsSync(iconPath)) {
        archive.file(iconPath, { name: "assets/icon-512.png" });
        hasIcon = true;
      }
    }

    archive.finalize();
  });
}
