/**
 * Browser-side Submission Pack Generator
 * Creates a ZIP file with all submission materials using JSZip
 */

import JSZip from "jszip";
import type { RuleEvaluationResult, GateFinding } from "./browser-scanner";

export interface SubmissionPackContents {
  hasReport: boolean;
  copyPasteFiles: string[];
  screenshots: string[];
  hasFeatureGraphic: boolean;
  hasIcon: boolean;
  checklists: string[];
}

export interface SubmissionPackResult {
  appName: string;
  generatedAt: string;
  blob: Blob;
  filename: string;
  contents: SubmissionPackContents;
}

export interface StoredAssets {
  ios: { screenshots: string[]; icon?: string };
  android: { screenshots: string[]; icon?: string; feature?: string };
}

/**
 * Sanitize a filename by removing invalid characters
 */
function sanitizeFilename(name: string): string {
  return name
    .replace(/[^a-zA-Z0-9_-]/g, "_")
    .replace(/_+/g, "_")
    .slice(0, 50);
}

/**
 * Format current date for filename (YYYYMMDD)
 */
function formatDateForFilename(): string {
  const now = new Date();
  const year = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, "0");
  const day = String(now.getDate()).padStart(2, "0");
  return `${year}${month}${day}`;
}

/**
 * Create a submission pack filename
 */
function createPackFilename(appName: string): string {
  const safeName = sanitizeFilename(appName);
  const date = formatDateForFilename();
  return `StorePreflight_SubmissionPack_${safeName}_${date}.zip`;
}

/**
 * Generate copy-paste text files from findings
 */
function generateCopyPasteFiles(findings: GateFinding[]): Map<string, string> {
  const files = new Map<string, string>();

  const appPurposes: string[] = [];
  const permissionJustifications: string[] = [];
  const reviewerNotes: string[] = [];
  const dataSafetyEntries: Record<string, string> = {};

  for (const finding of findings) {
    if (finding.copy.appPurpose) {
      appPurposes.push(`[${finding.id}]\n${finding.copy.appPurpose}`);
    }
    if (finding.copy.permissionJustification) {
      permissionJustifications.push(`[${finding.id}]\n${finding.copy.permissionJustification}`);
    }
    if (finding.copy.reviewerNotes) {
      reviewerNotes.push(`[${finding.id}]\n${finding.copy.reviewerNotes}`);
    }
    if (finding.copy.dataSafety) {
      dataSafetyEntries[finding.id] = finding.copy.dataSafety;
    }
  }

  if (appPurposes.length > 0) {
    files.set("google_app_purpose.txt", appPurposes.join("\n\n---\n\n"));
  }

  if (permissionJustifications.length > 0) {
    files.set("google_permission_justifications.txt", permissionJustifications.join("\n\n---\n\n"));
  }

  if (reviewerNotes.length > 0) {
    files.set("reviewer_notes.txt", reviewerNotes.join("\n\n---\n\n"));
  }

  if (Object.keys(dataSafetyEntries).length > 0) {
    files.set("data_safety.json", JSON.stringify(dataSafetyEntries, null, 2));
  }

  return files;
}

/**
 * Generate platform-specific checklists
 */
function generateChecklists(result: RuleEvaluationResult): Map<string, string> {
  const checklists = new Map<string, string>();

  const googleFindings = result.findings.filter(
    (f) => f.platform === "google" || f.platform === "both"
  );

  const appleFindings = result.findings.filter(
    (f) => f.platform === "apple" || f.platform === "both"
  );

  if (result.platformTargets.includes("android")) {
    const items = googleFindings.map((f) => {
      const checks: string[] = [];
      if (f.requires.video) checks.push("Upload YouTube demo video");
      if (f.requires.screenshots) checks.push("Prepare screenshots");
      if (f.requires.reviewerNotes) checks.push("Add reviewer notes");
      if (f.copy.permissionJustification) checks.push("Add permission justification");
      if (f.copy.dataSafety) checks.push("Complete Data Safety form");

      return checks.length > 0
        ? `## ${f.id}\n\n${checks.map((c) => `- [ ] ${c}`).join("\n")}`
        : null;
    }).filter(Boolean);

    if (items.length > 0) {
      checklists.set(
        "google-play.md",
        `# Google Play Console Checklist\n\nGenerated by StorePreflight on ${new Date().toLocaleDateString()}\n\n${items.join("\n\n")}`
      );
    }
  }

  if (result.platformTargets.includes("ios")) {
    const items = appleFindings.map((f) => {
      const checks: string[] = [];
      if (f.requires.screenshots) checks.push("Prepare screenshots");
      if (f.requires.reviewerNotes) checks.push("Add App Review notes");
      if (f.copy.permissionJustification) checks.push("Add usage description");

      return checks.length > 0
        ? `## ${f.id}\n\n${checks.map((c) => `- [ ] ${c}`).join("\n")}`
        : null;
    }).filter(Boolean);

    if (items.length > 0) {
      checklists.set(
        "app-store.md",
        `# App Store Connect Checklist\n\nGenerated by StorePreflight on ${new Date().toLocaleDateString()}\n\n${items.join("\n\n")}`
      );
    }
  }

  return checklists;
}

/**
 * Generate the HTML report content
 */
function generateHtmlReport(result: RuleEvaluationResult): string {
  const now = new Date().toISOString();

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>StorePreflight Report - ${result.appName}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #f5f5f5; color: #1a1a1a; line-height: 1.5; }
    .container { max-width: 800px; margin: 0 auto; padding: 2rem; }
    .header { background: linear-gradient(135deg, #2E7D32, #4CAF50); color: white; padding: 2rem; border-radius: 12px; margin-bottom: 2rem; }
    .header h1 { font-size: 1.75rem; margin-bottom: 0.5rem; }
    .header p { opacity: 0.9; }
    .meta { display: flex; gap: 2rem; margin-top: 1rem; font-size: 0.875rem; }
    .card { background: white; border-radius: 12px; padding: 1.5rem; margin-bottom: 1rem; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
    .card h2 { font-size: 1.125rem; margin-bottom: 1rem; color: #333; }
    .summary-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 1rem; }
    .summary-item { text-align: center; padding: 1rem; border-radius: 8px; }
    .summary-item.high { background: #fee2e2; color: #991b1b; }
    .summary-item.medium { background: #fef3c7; color: #92400e; }
    .summary-item.low { background: #dcfce7; color: #166534; }
    .summary-item .count { font-size: 2rem; font-weight: bold; }
    .finding { border: 1px solid #e5e7eb; border-radius: 8px; padding: 1rem; margin-bottom: 0.75rem; }
    .finding.blocking { border-color: #fca5a5; background: #fef2f2; }
    .finding-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 0.5rem; }
    .finding-id { font-weight: 600; }
    .badge { display: inline-block; padding: 0.25rem 0.5rem; border-radius: 4px; font-size: 0.75rem; font-weight: 500; margin-left: 0.25rem; }
    .badge.high { background: #fee2e2; color: #991b1b; }
    .badge.medium { background: #fef3c7; color: #92400e; }
    .badge.low { background: #dcfce7; color: #166534; }
    .badge.apple { background: #1a1a1a; color: white; }
    .badge.google { background: #dbeafe; color: #1e40af; }
    .badge.both { background: #f3e8ff; color: #6b21a8; }
    .copy-section { background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 8px; padding: 1rem; margin-top: 0.75rem; }
    .copy-section h4 { font-size: 0.875rem; color: #166534; margin-bottom: 0.5rem; }
    .copy-section p { font-size: 0.875rem; white-space: pre-wrap; }
    .footer { text-align: center; color: #6b7280; font-size: 0.875rem; margin-top: 2rem; padding-top: 2rem; border-top: 1px solid #e5e7eb; }
    .status { padding: 0.5rem 1rem; border-radius: 8px; font-weight: 600; display: inline-block; margin-top: 1rem; }
    .status.blocked { background: #fee2e2; color: #991b1b; }
    .status.ready { background: #dcfce7; color: #166534; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>📋 StorePreflight Report</h1>
      <p>${result.appName} (${result.bundleId})</p>
      <div class="meta">
        <span>Generated: ${new Date(now).toLocaleString()}</span>
        <span>Platforms: ${result.platformTargets.join(", ")}</span>
      </div>
      <div class="status ${result.summary.blocked ? "blocked" : "ready"}">
        ${result.summary.blocked ? "⚠️ BLOCKING ISSUES FOUND" : "✅ READY FOR SUBMISSION"}
      </div>
    </div>

    <div class="card">
      <h2>Summary</h2>
      <div class="summary-grid">
        <div class="summary-item high">
          <div class="count">${result.summary.high}</div>
          <div>High Risk</div>
        </div>
        <div class="summary-item medium">
          <div class="count">${result.summary.medium}</div>
          <div>Medium Risk</div>
        </div>
        <div class="summary-item low">
          <div class="count">${result.summary.low}</div>
          <div>Low Risk</div>
        </div>
      </div>
    </div>

    <div class="card">
      <h2>Findings (${result.findings.length})</h2>
      ${result.findings
        .map(
          (f) => `
        <div class="finding ${f.isBlocking ? "blocking" : ""}">
          <div class="finding-header">
            <span class="finding-id">${f.id}</span>
            <div>
              <span class="badge ${f.platform}">${f.platform.toUpperCase()}</span>
              <span class="badge ${f.risk}">${f.risk.toUpperCase()}${f.isBlocking ? " (BLOCKING)" : ""}</span>
            </div>
          </div>
          ${f.triggers.length > 0 ? `<p style="color:#6b7280;font-size:0.875rem;">Triggers: ${f.triggers.join(", ")}</p>` : ""}
          ${
            Object.entries(f.copy).length > 0
              ? `
            ${Object.entries(f.copy)
              .map(
                ([key, value]) => `
              <div class="copy-section">
                <h4>📋 ${key.replace(/([A-Z])/g, " $1").replace(/^./, (s) => s.toUpperCase())}</h4>
                <p>${value}</p>
              </div>
            `
              )
              .join("")}
          `
              : ""
          }
        </div>
      `
        )
        .join("")}
    </div>

    <div class="footer">
      <p>Generated by <strong>StorePreflight</strong></p>
      <p>Know what Apple and Google will ask before you submit.</p>
    </div>
  </div>
</body>
</html>`;
}

/**
 * Convert a data URL to a Uint8Array for ZIP inclusion
 */
function dataUrlToUint8Array(dataUrl: string): Uint8Array {
  const parts = dataUrl.split(",");
  const base64 = parts[1] ?? "";
  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.charCodeAt(i);
  }
  return bytes;
}

/**
 * Get file extension from data URL mime type
 */
function getExtensionFromDataUrl(dataUrl: string): string {
  const match = dataUrl.match(/data:image\/(\w+)/);
  if (match && match[1]) {
    const type = match[1];
    if (type === "jpeg") return "jpg";
    return type;
  }
  return "png";
}

export interface GenerateSubmissionPackOptions {
  result: RuleEvaluationResult;
  assets?: StoredAssets;
}

/**
 * Generate the complete submission pack ZIP in the browser
 */
export async function generateSubmissionPack(
  options: GenerateSubmissionPackOptions
): Promise<SubmissionPackResult> {
  const { result, assets } = options;
  const zip = new JSZip();

  const contents: SubmissionPackContents = {
    hasReport: true,
    copyPasteFiles: [],
    screenshots: [],
    hasFeatureGraphic: false,
    hasIcon: false,
    checklists: [],
  };

  // Add HTML report
  const htmlReport = generateHtmlReport(result);
  zip.file("reports/storepreflight.html", htmlReport);

  // Add copy-paste files
  const copyFiles = generateCopyPasteFiles(result.findings);
  for (const [filename, content] of copyFiles) {
    zip.file(`copy-paste/${filename}`, content);
    contents.copyPasteFiles.push(filename);
  }

  // Add checklists
  const checklistFiles = generateChecklists(result);
  for (const [filename, content] of checklistFiles) {
    zip.file(`checklists/${filename}`, content);
    contents.checklists.push(filename);
  }

  // Add assets if provided
  if (assets) {
    // Android screenshots
    if (assets.android.screenshots.length > 0) {
      assets.android.screenshots.forEach((dataUrl, index) => {
        const ext = getExtensionFromDataUrl(dataUrl);
        const filename = `screenshot_${index + 1}.${ext}`;
        zip.file(`assets/google-play/screenshots/${filename}`, dataUrlToUint8Array(dataUrl));
        contents.screenshots.push(`google-play/${filename}`);
      });
    }

    // Android feature graphic
    if (assets.android.feature) {
      const ext = getExtensionFromDataUrl(assets.android.feature);
      zip.file(`assets/google-play/feature-graphic.${ext}`, dataUrlToUint8Array(assets.android.feature));
      contents.hasFeatureGraphic = true;
    }

    // Android icon
    if (assets.android.icon) {
      const ext = getExtensionFromDataUrl(assets.android.icon);
      zip.file(`assets/google-play/icon-512.${ext}`, dataUrlToUint8Array(assets.android.icon));
      contents.hasIcon = true;
    }

    // iOS screenshots
    if (assets.ios.screenshots.length > 0) {
      assets.ios.screenshots.forEach((dataUrl, index) => {
        const ext = getExtensionFromDataUrl(dataUrl);
        const filename = `screenshot_${index + 1}.${ext}`;
        zip.file(`assets/app-store/screenshots/${filename}`, dataUrlToUint8Array(dataUrl));
        contents.screenshots.push(`app-store/${filename}`);
      });
    }

    // iOS icon
    if (assets.ios.icon) {
      const ext = getExtensionFromDataUrl(assets.ios.icon);
      zip.file(`assets/app-store/icon-1024.${ext}`, dataUrlToUint8Array(assets.ios.icon));
      if (!contents.hasIcon) contents.hasIcon = true;
    }
  }

  // Add a README
  const readme = `# StorePreflight Submission Pack

Generated: ${new Date().toLocaleString()}
App: ${result.appName} (${result.bundleId})
Platforms: ${result.platformTargets.join(", ")}

## Contents

### /reports
- storepreflight.html - Full HTML report with all findings

### /copy-paste
${contents.copyPasteFiles.length > 0 ? contents.copyPasteFiles.map((f) => `- ${f}`).join("\n") : "- (no copy-paste files generated)"}

### /checklists
${contents.checklists.length > 0 ? contents.checklists.map((f) => `- ${f}`).join("\n") : "- (no checklists generated)"}

### /assets
${contents.screenshots.length > 0 || contents.hasIcon || contents.hasFeatureGraphic ? "Screenshots and icons for store submission" : "- (no assets included)"}

## How to Use

1. Open the HTML report in your browser for a full overview
2. Use the copy-paste files when filling out store forms
3. Follow the platform checklists to ensure nothing is missed
4. Upload assets directly to App Store Connect / Google Play Console

---
Generated by StorePreflight - Know what Apple and Google will ask before you submit.
`;
  zip.file("README.md", readme);

  // Generate the ZIP blob
  const blob = await zip.generateAsync({ type: "blob" });
  const filename = createPackFilename(result.appName);

  return {
    appName: result.appName,
    generatedAt: new Date().toISOString(),
    blob,
    filename,
    contents,
  };
}
